on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  main:
    runs-on: self-hosted
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.*

      # - name: Databricks CLI config
      #   run: |
      #       curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      #       cat > ./.databrickscfg << EOF 
      #       [DEFAULT] 
      #       host = ${{ vars.DATABRICKS_HOST }} 
      #       token = ${{ secrets.DATABRICKS_TOKEN }} 
      #       jobs-api-version = 2.1 
      #       EOF
            
      # - name: install-databricks-cli
      #   uses: microsoft/install-databricks-cli@v1.0.0

      - name: Databricks CLI config
        run: |
            # @echo off
            set "DATABRICKS_HOST=${{ vars.DATABRICKS_HOST }}"
            set "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}"
            curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh -o install.sh
            bash install.sh
            echo [DEFAULT] > .\.databrickscfg
            echo host = %DATABRICKS_HOST% >> .\.databrickscfg
            echo token = %DATABRICKS_TOKEN% >> .\.databrickscfg
            echo jobs-api-version = 2.1 >> .\.databrickscfg

      
      - name: Deploy code to databricks workspace
        run: |
            databricks workspace import-dir "${{github.workspace}}/src" "/Shared" --overwrite
