on:
  push:
    branches:
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Databricks CLI config
        run: |
            pip install databricks-cli 
            cat > ~/.databrickscfg << EOF 
            [DEFAULT] 
            host = ${{ vars.DATABRICKS_HOST }} 
            token = ${{ secrets.DATABRICKS_TOKEN }} 
            jobs-api-version = 2.1 
            EOF
    
      - name: Deploy code to databricks workspace
        run: |
            databricks workspace import-dir "${{github.workspace}}/src" "/Shared/src" --language python --overwrite
